import type { GenerationConfig } from "./types";

export const GENERATIONS: GenerationConfig[] = [
  {
    slug: "gen-alpha",
    name: "Gen Alpha",
    era: "2010s–Present",
    color: "var(--color-pill-8)",
    emoji: "🧠",
    tagline: "Brainrot, rizz, and skibidi vibes",
  },
  {
    slug: "gen-z",
    name: "Gen Z",
    era: "1997–2012",
    color: "var(--color-pill-7)",
    emoji: "💅",
    tagline: "No cap, it's giving main character energy",
  },
  {
    slug: "gen-y",
    name: "Millennials",
    era: "1981–1996",
    color: "var(--color-pill-6)",
    emoji: "📱",
    tagline: "YOLO, adulting, and pumpkin spice everything",
  },
  {
    slug: "gen-x",
    name: "Gen X",
    era: "1965–1980",
    color: "var(--color-accent)",
    emoji: "🎸",
    tagline: "Whatever — all that and a bag of chips",
  },
  {
    slug: "gen-boomers",
    name: "Boomers",
    era: "1946–1964",
    color: "var(--color-pill-2)",
    emoji: "✌️",
    tagline: "Groovy, far out, and flower power",
  },
  {
    slug: "gen-silent",
    name: "Silent Gen",
    era: "1928–1945",
    color: "var(--color-accent-700)",
    emoji: "🎩",
    tagline: "Swell, the bee's knees, and daddy-o",
  },
];

export function getGeneration(slug: string): GenerationConfig | undefined {
  return GENERATIONS.find((g) => g.slug === slug);
}

// Translator word maps per generation
export const TRANSLATOR_MAPS: Record<string, Record<string, string>> = {
  "gen-alpha": {
    good: "bussin",
    great: "goated",
    amazing: "no cap slay",
    cool: "rizz",
    awesome: "based",
    really: "fr fr",
    very: "lowkey",
    bad: "L",
    terrible: "mid",
    win: "W",
    lose: "L",
    friend: "bestie",
    friends: "the lobby",
    hello: "yo",
    hi: "sup",
    leave: "dip",
    weird: "ohio",
    crazy: "skibidi",
    serious: "no cap",
    agree: "bet",
    yes: "bet",
    okay: "aight",
    funny: "sending me",
    embarrassing: "caught in 4K",
    attractive: "rizz",
    ugly: "mid",
    brag: "glazing",
    perfect: "ate and left no crumbs",
    boring: "NPC behavior",
  },
  "gen-z": {
    good: "it slaps",
    great: "understood the assignment",
    amazing: "ate and left no crumbs",
    cool: "slay",
    awesome: "periodt",
    really: "no cap",
    very: "it's giving",
    bad: "not it",
    terrible: "red flag",
    win: "understood the assignment",
    friend: "bestie",
    friends: "the besties",
    hello: "hey bestie",
    leave: "dip",
    weird: "beige flag",
    serious: "no cap",
    agree: "bet",
    yes: "periodt",
    okay: "slay",
    funny: "I'm crying",
    attractive: "snatched",
    brag: "soft launch",
    perfect: "slay",
    boring: "cheugy",
  },
  "gen-y": {
    good: "YOLO",
    great: "slay",
    amazing: "on fleek",
    cool: "goals",
    awesome: "lit",
    really: "literally",
    very: "so",
    bad: "basic",
    terrible: "triggering",
    win: "goals",
    friend: "fam",
    friends: "squad",
    hello: "hey fam",
    leave: "bounce",
    weird: "extra",
    serious: "TBH",
    agree: "I can't even",
    yes: "yaas",
    okay: "I guess",
    funny: "I'm dead",
    attractive: "snatched",
    brag: "humble brag",
    perfect: "on fleek",
    boring: "basic",
  },
  "gen-x": {
    good: "dope",
    great: "da bomb",
    amazing: "phat",
    cool: "fly",
    awesome: "radical",
    really: "hella",
    very: "mad",
    bad: "wack",
    terrible: "totally bogus",
    win: "booyah",
    friend: "homeslice",
    friends: "crew",
    hello: "yo",
    hi: "wassup",
    leave: "bounce",
    weird: "trippin",
    serious: "fo real",
    agree: "word",
    yes: "word",
    okay: "aight",
    funny: "hella funny",
    attractive: "fly",
    brag: "frontin",
    perfect: "da bomb",
    boring: "whatever",
  },
  "gen-boomers": {
    good: "groovy",
    great: "far out",
    amazing: "out of sight",
    cool: "hip",
    awesome: "psychedelic",
    really: "heavy",
    very: "mad",
    bad: "bummer",
    terrible: "bogus",
    win: "right on",
    friend: "cat",
    friends: "the gang",
    hello: "hey man",
    leave: "split",
    weird: "trippy",
    serious: "heavy",
    agree: "right on",
    yes: "dig it",
    okay: "solid",
    funny: "a trip",
    attractive: "foxy",
    brag: "ego trip",
    perfect: "boss",
    boring: "drag",
  },
  "gen-silent": {
    good: "swell",
    great: "the bee's knees",
    amazing: "the cat's meow",
    cool: "hep",
    awesome: "cooking with gas",
    really: "quite",
    very: "real",
    bad: "what a drag",
    terrible: "behind the eight ball",
    win: "made in the shade",
    friend: "pal",
    friends: "the gang",
    hello: "hiya",
    leave: "scram",
    weird: "odd duck",
    serious: "on the level",
    agree: "that's the ticket",
    yes: "you bet",
    okay: "swell",
    funny: "a real gas",
    attractive: "dreamboat",
    brag: "putting on airs",
    perfect: "keen",
    boring: "a square",
  },
};
