/** Canonical Gen Alpha → Gen X equivalence map (keyed by gen-alpha term id) */
export const GEN_X_MAP: Record<string, string> = {
  skibidi: "Gnarly / Radical",
  rizz: "Game / Mack Daddy",
  bussin: "Da Bomb / Phat",
  "no-cap": "Word / Keeping It Real",
  sus: "Sketchy",
  slay: "Fly / All That",
  bet: "Word / Aight",
  mid: "Wack / Whatever",
  brainrot: "Couch Potato / Vegging Out",
  "fanum-tax": "Bogart",
  ohio: "Twilight Zone",
  sigma: "Lone Wolf",
  gyatt: "Schwing",
  mewing: "Keeping It Real",
  aura: "Vibe",
  ratio: "Diss / Burn",
  cap: "NOT! / Psych!",
  delulu: "Trippin'",
  w: "Booyah",
  l: "Bummer",
  npc: "Scrub / Poser",
  goat: "All That and a Bag of Chips",
  fire: "Da Bomb / Dope",
  drip: "Fly / Fresh",
  "hits-different": "Phat / Tight",
  "vibe-check": "What's the 411",
  ate: "Killed It / Nailed It",
  ick: "Gag Me with a Spoon",
  stan: "Groupie / Super Fan",
  ghosting: "Bounce / Dip",
  yeet: "Chuck / Hurl",
  flex: "Frontin' / Showing Off",
  simp: "Whipped",
  based: "Radical / Keeping It Real",
  lowkey: "On the DL",
  highkey: "Totally / Hella",
  "sending-me": "Cracking Up",
  "understood-the-assignment": "Nailed It",
  "main-character": "All That",
  "touch-grass": "Take a Chill Pill",
  "rent-free": "Living In Your Head",
  "caught-in-4k": "Busted",
  periodt: "Word / Fo Shizzle",
  // Coverage for existing gen-alpha seed terms that previously had no map entry.
  lit: "Off the Hook",
  vibe: "The Mood / Scene",
  slaps: "Bangin' / Jammin'",
  finna: "Fixin' To",
  mood: "Same / Story of My Life",
  salty: "Sour Grapes",
  tea: "Scoop / Dirt",
  sheesh: "Whoa! / Damn!",
  savage: "Cold-Blooded",
  cringe: "Cheesy / Eye Roll",
  ghosted: "Cold Shoulder / Blew Off",
  "glow-up": "Makeover / Comeback",
  shade: "Snub / Dig",
  "big-yikes": "Oof / Yikes",
  basic: "Vanilla / Mainstream",
  boujee: "Bougie / Yuppie",
  cancelled: "Blackballed / Blacklisted",
  hella: "Wicked / Mad",
  bestie: "BFF / Bud",
  deadass: "Dead Serious",
  "on-god": "Swear To God",
  "fr-fr": "Honestly / No Joke",
  "ok-boomer": "Whatever, Grandma",
  snatched: "On Point / Sharp",
};
