-- Seed data for the Dad Joke of the Day catalog. Ships to every environment
-- via `supabase db push`. Idempotent — re-running this migration will not
-- duplicate rows; it claims any pre-existing rows (e.g. from local seed.sql
-- runs) and stamps them with seed_source = 'dad_jokes_v1'.
--
-- Pattern (see docs/guides/migrations.md "Data migrations"):
--   * `seed_source text` column tags rows owned by a specific seed batch.
--   * `unique (setup, punchline)` lets us use ON CONFLICT for idempotent re-runs.
--   * Rolling back deletes only this batch's rows (not user-created jokes).

alter table public.dad_jokes
  add column if not exists seed_source text;

create index if not exists idx_dad_jokes_seed_source
  on public.dad_jokes (seed_source) where seed_source is not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'dad_jokes_setup_punchline_key'
      and conrelid = 'public.dad_jokes'::regclass
  ) then
    alter table public.dad_jokes
      add constraint dad_jokes_setup_punchline_key unique (setup, punchline);
  end if;
end $$;

insert into public.dad_jokes (setup, punchline, category, seed_source) values
  ('Why don''t oysters give to charity?', 'Because they''re shellfish.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a bear with no teeth?', 'A gummy bear.', 'Animals', 'dad_jokes_v1'),
  ('How does a penguin build its house?', 'Igloos it together.', 'Animals', 'dad_jokes_v1'),
  ('Why did the chicken cross the playground?', 'To get to the other slide.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a cow during an earthquake?', 'A milkshake.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a deer with no eyes?', 'No idea.', 'Animals', 'dad_jokes_v1'),
  ('Why was the horse so polite?', 'It had stable manners.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a pig that does karate?', 'A pork chop.', 'Animals', 'dad_jokes_v1'),
  ('What''s a frog''s favorite snack?', 'French flies.', 'Animals', 'dad_jokes_v1'),
  ('Why don''t seagulls fly over the bay?', 'Because then they''d be bagels.', 'Animals', 'dad_jokes_v1'),
  ('Why don''t elephants use computers?', 'They''re afraid of the mouse.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a snake that''s exactly 3.14 meters long?', 'A pi-thon.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a sleeping bull?', 'A bulldozer.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a parade of rabbits hopping backwards?', 'A receding hare-line.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a fish wearing a crown?', 'Your royal haddock.', 'Animals', 'dad_jokes_v1'),
  ('Why don''t koalas count as bears?', 'They don''t have the right koala-fications.', 'Animals', 'dad_jokes_v1'),
  ('How do you catch a squirrel?', 'Climb a tree and act like a nut.', 'Animals', 'dad_jokes_v1'),
  ('What''s a cat''s favorite color?', 'Purr-ple.', 'Animals', 'dad_jokes_v1'),
  ('Why did the leopard wear a striped shirt?', 'So he wouldn''t be spotted.', 'Animals', 'dad_jokes_v1'),
  ('What''s a shark''s favorite sandwich?', 'Peanut butter and jellyfish.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a cold dog?', 'A chili dog.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a dog that does magic?', 'A labracadabrador.', 'Animals', 'dad_jokes_v1'),
  ('What did the buffalo say to his son leaving for school?', 'Bison.', 'Animals', 'dad_jokes_v1'),
  ('What''s a frog''s favorite year?', 'A leap year.', 'Animals', 'dad_jokes_v1'),
  ('Why did the cow cross the road?', 'To get to the udder side.', 'Animals', 'dad_jokes_v1'),
  ('Why are owls invited to every party?', 'They''re always a hoot.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a duck that gets all A''s?', 'A wise quacker.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a llama who can sing?', 'A llamapella.', 'Animals', 'dad_jokes_v1'),
  ('Why don''t ants ever get sick?', 'They have tiny anty-bodies.', 'Animals', 'dad_jokes_v1'),
  ('What do you call an alligator detective?', 'An investi-gator.', 'Animals', 'dad_jokes_v1'),
  ('What do you call a fake noodle?', 'An impasta.', 'Food', 'dad_jokes_v1'),
  ('Why did the tomato turn red?', 'Because it saw the salad dressing.', 'Food', 'dad_jokes_v1'),
  ('What did the grape say when it got stepped on?', 'Nothing — it just let out a little wine.', 'Food', 'dad_jokes_v1'),
  ('How do you fix a broken pizza?', 'With tomato paste.', 'Food', 'dad_jokes_v1'),
  ('Why don''t eggs tell jokes?', 'They''d crack each other up.', 'Food', 'dad_jokes_v1'),
  ('What does a nosy pepper do?', 'Gets jalapeño business.', 'Food', 'dad_jokes_v1'),
  ('What do you call cheese that isn''t yours?', 'Nacho cheese.', 'Food', 'dad_jokes_v1'),
  ('What did the hamburger name its daughter?', 'Patty.', 'Food', 'dad_jokes_v1'),
  ('Why did the coffee file a police report?', 'It got mugged.', 'Food', 'dad_jokes_v1'),
  ('Why did the banana go to the doctor?', 'It wasn''t peeling well.', 'Food', 'dad_jokes_v1'),
  ('What do you call a melon that can''t get married?', 'Cantaloupe.', 'Food', 'dad_jokes_v1'),
  ('How does a cucumber become a pickle?', 'It goes through a jarring experience.', 'Food', 'dad_jokes_v1'),
  ('What do you give a sick lemon?', 'Lemon-aid.', 'Food', 'dad_jokes_v1'),
  ('Why did the mushroom get invited everywhere?', 'Because he was a fungi.', 'Food', 'dad_jokes_v1'),
  ('Why didn''t the orange win the race?', 'It ran out of juice.', 'Food', 'dad_jokes_v1'),
  ('Why did the donut visit the dentist?', 'To get a filling.', 'Food', 'dad_jokes_v1'),
  ('What''s a vampire''s favorite fruit?', 'A neck-tarine.', 'Food', 'dad_jokes_v1'),
  ('How do you make a milkshake?', 'You give a cow a scary movie.', 'Food', 'dad_jokes_v1'),
  ('What did one plate say to the other?', 'Dinner''s on me.', 'Food', 'dad_jokes_v1'),
  ('Why was the cucumber upset?', 'It was in a pickle.', 'Food', 'dad_jokes_v1'),
  ('Why did the lettuce blush?', 'It saw the salad dressing.', 'Food', 'dad_jokes_v1'),
  ('Why was the strawberry so stressed?', 'It was in a jam.', 'Food', 'dad_jokes_v1'),
  ('Why did the toast cry?', 'It missed its loaf.', 'Food', 'dad_jokes_v1'),
  ('What do you call sad coffee?', 'A depresso.', 'Food', 'dad_jokes_v1'),
  ('Why don''t hot dogs argue?', 'They can''t relish the conflict.', 'Food', 'dad_jokes_v1'),
  ('What did the bacon say to the tomato?', 'Lettuce get together.', 'Food', 'dad_jokes_v1'),
  ('Why did the cookie go to the doctor?', 'Because it felt crummy.', 'Food', 'dad_jokes_v1'),
  ('What kind of tea is hard to swallow?', 'Reality.', 'Food', 'dad_jokes_v1'),
  ('Why did the bread break up with the butter?', 'It found someone better.', 'Food', 'dad_jokes_v1'),
  ('What did the salt say to the pepper?', 'Hey there, season-er or later.', 'Food', 'dad_jokes_v1'),
  ('I''m reading a book about anti-gravity.', 'It''s impossible to put down.', 'Wordplay', 'dad_jokes_v1'),
  ('I used to hate facial hair.', 'But then it grew on me.', 'Wordplay', 'dad_jokes_v1'),
  ('I''m on a seafood diet.', 'I see food and I eat it.', 'Wordplay', 'dad_jokes_v1'),
  ('I told my wife she should embrace her mistakes.', 'She gave me a hug.', 'Wordplay', 'dad_jokes_v1'),
  ('Time flies like an arrow.', 'Fruit flies like a banana.', 'Wordplay', 'dad_jokes_v1'),
  ('I would tell you a construction joke.', 'But I''m still working on it.', 'Wordplay', 'dad_jokes_v1'),
  ('I would tell you a chemistry joke.', 'But I know I wouldn''t get a reaction.', 'Wordplay', 'dad_jokes_v1'),
  ('I tried to catch fog yesterday.', 'I mist.', 'Wordplay', 'dad_jokes_v1'),
  ('I''m afraid for the calendar.', 'Its days are numbered.', 'Wordplay', 'dad_jokes_v1'),
  ('I used to be a banker.', 'But then I lost interest.', 'Wordplay', 'dad_jokes_v1'),
  ('Velcro?', 'What a rip-off.', 'Wordplay', 'dad_jokes_v1'),
  ('Did you hear about the claustrophobic astronaut?', 'He just needed a little space.', 'Wordplay', 'dad_jokes_v1'),
  ('I don''t trust stairs.', 'They''re always up to something.', 'Wordplay', 'dad_jokes_v1'),
  ('I gave all my dead batteries away.', 'Free of charge.', 'Wordplay', 'dad_jokes_v1'),
  ('I bought some shoes from a drug dealer.', 'I don''t know what he laced them with, but I was tripping all day.', 'Wordplay', 'dad_jokes_v1'),
  ('I''m reading a book about helium.', 'I just can''t put it down.', 'Wordplay', 'dad_jokes_v1'),
  ('I told my dog he was adopted.', 'He took it ruff.', 'Wordplay', 'dad_jokes_v1'),
  ('I used to be addicted to the hokey pokey.', 'But I turned myself around.', 'Wordplay', 'dad_jokes_v1'),
  ('I tried to write with a broken pencil.', 'It was pointless.', 'Wordplay', 'dad_jokes_v1'),
  ('The rotation of Earth?', 'It really makes my day.', 'Wordplay', 'dad_jokes_v1'),
  ('I lost my job at the calendar factory.', 'I just took a few days off.', 'Wordplay', 'dad_jokes_v1'),
  ('The shovel.', 'Truly a groundbreaking invention.', 'Wordplay', 'dad_jokes_v1'),
  ('Singing in the shower is fun until you get soap in your mouth.', 'Then it''s a soap opera.', 'Wordplay', 'dad_jokes_v1'),
  ('I told my carpenter not to drink.', 'But he hammered anyway.', 'Wordplay', 'dad_jokes_v1'),
  ('I don''t trust atoms.', 'They make up everything.', 'Wordplay', 'dad_jokes_v1'),
  ('I''ve been told I''m condescending.', 'That means I talk down to people.', 'Wordplay', 'dad_jokes_v1'),
  ('Did you hear about the kidnapping at school?', 'It''s fine — he woke up.', 'Wordplay', 'dad_jokes_v1'),
  ('I tried writing a song in 4/4.', 'But it''s a measure I can''t keep.', 'Wordplay', 'dad_jokes_v1'),
  ('Why did the developer go broke?', 'He used up all his cache.', 'Tech', 'dad_jokes_v1'),
  ('Why do programmers prefer dark mode?', 'Because light attracts bugs.', 'Tech', 'dad_jokes_v1'),
  ('How many programmers does it take to change a lightbulb?', 'None — that''s a hardware problem.', 'Tech', 'dad_jokes_v1'),
  ('Why was the JavaScript developer sad?', 'Because he didn''t Node how to Express himself.', 'Tech', 'dad_jokes_v1'),
  ('What''s a programmer''s favorite hangout?', 'The Foo Bar.', 'Tech', 'dad_jokes_v1'),
  ('Why do Java developers wear glasses?', 'Because they don''t C#.', 'Tech', 'dad_jokes_v1'),
  ('There are 10 types of people in the world.', 'Those who understand binary and those who don''t.', 'Tech', 'dad_jokes_v1'),
  ('Why did the computer go to therapy?', 'It had too many issues.', 'Tech', 'dad_jokes_v1'),
  ('Why was the robot tired?', 'He had a hard drive.', 'Tech', 'dad_jokes_v1'),
  ('How does a hacker escape the police?', 'He just ransomwares.', 'Tech', 'dad_jokes_v1'),
  ('What did the router say to the doctor?', 'It hurts when IP.', 'Tech', 'dad_jokes_v1'),
  ('Why did the function break up with the loop?', 'It said: you go on without me.', 'Tech', 'dad_jokes_v1'),
  ('What''s an AI''s favorite snack?', 'Microchips.', 'Tech', 'dad_jokes_v1'),
  ('Why was the SQL query lonely?', 'It had no relations.', 'Tech', 'dad_jokes_v1'),
  ('Why did the developer quit?', 'He didn''t get arrays.', 'Tech', 'dad_jokes_v1'),
  ('What''s a pirate''s favorite programming language?', 'Arrr.', 'Tech', 'dad_jokes_v1'),
  ('What do you call a slow IT guy?', 'Buffering.', 'Tech', 'dad_jokes_v1'),
  ('Why don''t keyboards sleep?', 'They have two shifts.', 'Tech', 'dad_jokes_v1'),
  ('Why did the laptop go to the dentist?', 'It had a Bluetooth.', 'Tech', 'dad_jokes_v1'),
  ('Why did the database go to therapy?', 'It had too many relationship issues.', 'Tech', 'dad_jokes_v1'),
  ('Why did the musician get arrested?', 'He was in treble.', 'Music', 'dad_jokes_v1'),
  ('What''s a skeleton''s favorite instrument?', 'The trom-bone.', 'Music', 'dad_jokes_v1'),
  ('How do you fix a broken brass instrument?', 'With a tuba glue.', 'Music', 'dad_jokes_v1'),
  ('What rock group has four men who don''t sing?', 'Mount Rushmore.', 'Music', 'dad_jokes_v1'),
  ('What''s a pirate''s favorite note?', 'High C.', 'Music', 'dad_jokes_v1'),
  ('Why did the bass player get kicked out?', 'He kept losing the beat.', 'Music', 'dad_jokes_v1'),
  ('What kind of music do mummies listen to?', 'Wrap.', 'Music', 'dad_jokes_v1'),
  ('Why did the singer climb a ladder?', 'To reach the high notes.', 'Music', 'dad_jokes_v1'),
  ('What do you call a cow that plays guitar?', 'A moosician.', 'Music', 'dad_jokes_v1'),
  ('Why did the drummer keep a key on his snare?', 'To unlock the rhythm.', 'Music', 'dad_jokes_v1'),
  ('How does Beethoven''s hair look?', 'A little Bach-combed.', 'Music', 'dad_jokes_v1'),
  ('Why did the violinist take notes during the concert?', 'He was always sharp.', 'Music', 'dad_jokes_v1'),
  ('Why don''t choirs ever get lost?', 'They always find their pitch.', 'Music', 'dad_jokes_v1'),
  ('What''s a DJ''s favorite cereal?', 'Sound bites.', 'Music', 'dad_jokes_v1'),
  ('Why don''t scientists trust atoms?', 'Because they make up everything.', 'Science', 'dad_jokes_v1'),
  ('What did the limestone say to the geologist?', 'Don''t take me for granite.', 'Science', 'dad_jokes_v1'),
  ('What did Mars say to Saturn?', 'Give me a ring sometime.', 'Science', 'dad_jokes_v1'),
  ('How does the moon cut his hair?', 'Eclipse it.', 'Science', 'dad_jokes_v1'),
  ('What do you call an educated tube?', 'A graduated cylinder.', 'Science', 'dad_jokes_v1'),
  ('Why is the ocean salty?', 'The land never waves back.', 'Science', 'dad_jokes_v1'),
  ('Why did the physicist break up with the biologist?', 'There was no chemistry.', 'Science', 'dad_jokes_v1'),
  ('What did the thermometer say to the graduated cylinder?', 'You may have graduated, but I have many degrees.', 'Science', 'dad_jokes_v1'),
  ('Why don''t black holes throw parties?', 'They suck the life out of everything.', 'Science', 'dad_jokes_v1'),
  ('Why did the photon check no luggage?', 'It was traveling light.', 'Science', 'dad_jokes_v1'),
  ('Why is gravity so trustworthy?', 'It never lets you down.', 'Science', 'dad_jokes_v1'),
  ('Why did the chemist read so slowly?', 'He was studying periodic tables.', 'Science', 'dad_jokes_v1'),
  ('What did one electron say to another?', 'Don''t get so negative.', 'Science', 'dad_jokes_v1'),
  ('Why did the photon refuse a tip?', 'It was already light.', 'Science', 'dad_jokes_v1'),
  ('Why are biology teachers always in trouble?', 'They keep crossing their genes.', 'Science', 'dad_jokes_v1'),
  ('What''s the chemical formula for sea water?', 'CH-2-O.', 'Science', 'dad_jokes_v1'),
  ('Why did the volcano break up with the mountain?', 'He had too much pressure.', 'Science', 'dad_jokes_v1'),
  ('Why did the soccer ball quit the team?', 'It was tired of being kicked around.', 'Sports', 'dad_jokes_v1'),
  ('Why are basketball players messy eaters?', 'They love to dribble.', 'Sports', 'dad_jokes_v1'),
  ('What do you call a baseball player who''s also a dad?', 'A pop fly.', 'Sports', 'dad_jokes_v1'),
  ('Why don''t you ever see hippos hiding in trees?', 'Because they''re really good at it.', 'Sports', 'dad_jokes_v1'),
  ('Why did the golfer wear two pairs of pants?', 'In case he got a hole in one.', 'Sports', 'dad_jokes_v1'),
  ('Why was Cinderella so bad at soccer?', 'She kept running away from the ball.', 'Sports', 'dad_jokes_v1'),
  ('Why did the bowling pin get a job?', 'He was tired of being knocked down.', 'Sports', 'dad_jokes_v1'),
  ('Why is bowling so quiet?', 'You can hear a pin drop.', 'Sports', 'dad_jokes_v1'),
  ('Why don''t grasshoppers go to football games?', 'They prefer cricket.', 'Sports', 'dad_jokes_v1'),
  ('What do a hockey player and a magician have in common?', 'Both pull off hat tricks.', 'Sports', 'dad_jokes_v1'),
  ('Why did the runner refuse to wear his watch?', 'He didn''t have time.', 'Sports', 'dad_jokes_v1'),
  ('Why did the football coach shake the vending machine?', 'He needed a quarter back.', 'Sports', 'dad_jokes_v1'),
  ('What''s a boxer''s favorite drink?', 'Punch.', 'Sports', 'dad_jokes_v1'),
  ('Why did the swimmer cross the road?', 'To get to the deep end.', 'Sports', 'dad_jokes_v1'),
  ('Why are gymnasts so balanced?', 'They flip out when they''re not.', 'Sports', 'dad_jokes_v1'),
  ('Why was the equal sign so humble?', 'He realized he wasn''t less than or greater than anyone.', 'Math', 'dad_jokes_v1'),
  ('Why is six afraid of seven?', 'Because seven eight nine.', 'Math', 'dad_jokes_v1'),
  ('Why do plants hate math?', 'It gives them square roots.', 'Math', 'dad_jokes_v1'),
  ('Why did the obtuse angle go to the beach?', 'Because it was over 90 degrees.', 'Math', 'dad_jokes_v1'),
  ('What''s a math teacher''s favorite tree?', 'A geometree.', 'Math', 'dad_jokes_v1'),
  ('Why did the student wear glasses in math class?', 'To improve di-vision.', 'Math', 'dad_jokes_v1'),
  ('Why couldn''t the angle get a loan?', 'His parents wouldn''t cosine.', 'Math', 'dad_jokes_v1'),
  ('Why did the two 4s skip lunch?', 'They already 8.', 'Math', 'dad_jokes_v1'),
  ('What do you call a number that can''t keep still?', 'A roamin'' numeral.', 'Math', 'dad_jokes_v1'),
  ('Why was the math book sad?', 'It had too many problems.', 'Math', 'dad_jokes_v1'),
  ('Why is statistics never the life of the party?', 'Because it''s mean.', 'Math', 'dad_jokes_v1'),
  ('Why did the calculator go to therapy?', 'It had too many functions.', 'Math', 'dad_jokes_v1'),
  ('Why was the geometry teacher so calm?', 'He had all the right angles.', 'Math', 'dad_jokes_v1'),
  ('What did zero say to eight?', 'Nice belt.', 'Math', 'dad_jokes_v1'),
  ('Why did the fraction get a divorce?', 'They didn''t have common denominators.', 'Math', 'dad_jokes_v1'),
  ('Why was the coffee mug promoted?', 'It always picked up the slack.', 'Work', 'dad_jokes_v1'),
  ('Why did the office worker bring a ladder?', 'He wanted to climb the corporate ladder.', 'Work', 'dad_jokes_v1'),
  ('Why don''t stand-up comics work in offices?', 'They can''t deal with the cubicle silence.', 'Work', 'dad_jokes_v1'),
  ('Why was the meeting so cold?', 'It had too many ice breakers.', 'Work', 'dad_jokes_v1'),
  ('Why did the email go to therapy?', 'It had too many attachments.', 'Work', 'dad_jokes_v1'),
  ('Why do accountants make great DJs?', 'They have all the spreadsheets dropping.', 'Work', 'dad_jokes_v1'),
  ('Why did the project manager bring a ladder to the meeting?', 'To raise the bar.', 'Work', 'dad_jokes_v1'),
  ('Why was the new printer so emotional?', 'It had a lot of issues with paper.', 'Work', 'dad_jokes_v1'),
  ('Why don''t elevators ever go to therapy?', 'They have too many ups and downs.', 'Work', 'dad_jokes_v1'),
  ('Why did the calendar apply for a job?', 'Its days were numbered.', 'Work', 'dad_jokes_v1'),
  ('Why was the boss late to the picnic?', 'He couldn''t find any vacation days.', 'Work', 'dad_jokes_v1'),
  ('Why did the resume blush?', 'It had too many references.', 'Work', 'dad_jokes_v1'),
  ('Why did the student eat his homework?', 'The teacher said it was a piece of cake.', 'School', 'dad_jokes_v1'),
  ('Why did the kid bring a ladder to school?', 'To go to high school.', 'School', 'dad_jokes_v1'),
  ('Why was the broom late to class?', 'It overswept.', 'School', 'dad_jokes_v1'),
  ('Why was the geometry book always tired?', 'It had too many angles to deal with.', 'School', 'dad_jokes_v1'),
  ('Why did the clock get sent to the principal?', 'It was tocking too much.', 'School', 'dad_jokes_v1'),
  ('Why did the teacher wear sunglasses?', 'Because her students were so bright.', 'School', 'dad_jokes_v1'),
  ('What did the pen say to the paper?', 'I dot my i''s on you.', 'School', 'dad_jokes_v1'),
  ('Why didn''t the sun go to college?', 'It already had a million degrees.', 'School', 'dad_jokes_v1'),
  ('Why was the music teacher locked out of class?', 'Her keys were on the piano.', 'School', 'dad_jokes_v1'),
  ('Why did the eraser go to therapy?', 'It couldn''t get over the past.', 'School', 'dad_jokes_v1'),
  ('Why don''t books trust pencils?', 'They always have a point.', 'School', 'dad_jokes_v1'),
  ('Why did the chalk break up with the eraser?', 'They had different points of view.', 'School', 'dad_jokes_v1'),
  ('Why was the school clock punished?', 'It always struck out.', 'School', 'dad_jokes_v1'),
  ('Why did the skeleton refuse to fight?', 'He didn''t have the guts.', 'Body', 'dad_jokes_v1'),
  ('Why don''t skeletons go to parties?', 'They have no body to go with.', 'Body', 'dad_jokes_v1'),
  ('Why did the hipster burn his tongue?', 'He drank his coffee before it was cool.', 'Body', 'dad_jokes_v1'),
  ('Why did the nose feel left out?', 'It never got picked.', 'Body', 'dad_jokes_v1'),
  ('Why was the foot embarrassed?', 'It saw the toe-mato.', 'Body', 'dad_jokes_v1'),
  ('Why did the heart fail anatomy?', 'It didn''t have a chamber to spare.', 'Body', 'dad_jokes_v1'),
  ('Why was the brain proud?', 'It used its head.', 'Body', 'dad_jokes_v1'),
  ('Why did the hair go to the gym?', 'To get more volume.', 'Body', 'dad_jokes_v1'),
  ('Why did the elbow blush?', 'It saw the funny bone.', 'Body', 'dad_jokes_v1'),
  ('Why don''t shoulders gossip?', 'They never carry baggage.', 'Body', 'dad_jokes_v1'),
  ('Why did the eye go to school?', 'To improve its vision.', 'Body', 'dad_jokes_v1'),
  ('Why don''t pilots ever get lost?', 'They follow plane sight.', 'Travel', 'dad_jokes_v1'),
  ('What did the airplane say to the airport?', 'I''ll catch you on the runway.', 'Travel', 'dad_jokes_v1'),
  ('Why was the suitcase so well-traveled?', 'It always packed light.', 'Travel', 'dad_jokes_v1'),
  ('What''s a sailor''s favorite letter?', 'The C.', 'Travel', 'dad_jokes_v1'),
  ('Why did the bicycle fall over?', 'It was two-tired.', 'Travel', 'dad_jokes_v1'),
  ('Why don''t traffic lights ever go skinny dipping?', 'They take too long to change.', 'Travel', 'dad_jokes_v1'),
  ('Why did the road go to therapy?', 'It had a rough commute.', 'Travel', 'dad_jokes_v1'),
  ('Why is the GPS such a know-it-all?', 'It always has the directions.', 'Travel', 'dad_jokes_v1'),
  ('Why don''t trains ever get sick?', 'They have great loco-motion.', 'Travel', 'dad_jokes_v1'),
  ('Why did the tourist visit the bakery in Paris?', 'He kneaded a vacation.', 'Travel', 'dad_jokes_v1'),
  ('Why are maps so dramatic?', 'They always have an unfolding story.', 'Travel', 'dad_jokes_v1'),
  ('What''s a tornado''s favorite game?', 'Twister.', 'Weather', 'dad_jokes_v1'),
  ('Why don''t clouds ever get stressed?', 'They just float through life.', 'Weather', 'dad_jokes_v1'),
  ('What did the cloud wear under his raincoat?', 'Thunderwear.', 'Weather', 'dad_jokes_v1'),
  ('Why was the lightning bolt blushing?', 'It saw the wind blow.', 'Weather', 'dad_jokes_v1'),
  ('Why did the sun go to school?', 'To get brighter.', 'Weather', 'dad_jokes_v1'),
  ('What''s the weather forecast for upset stomachs?', 'Reigning supreme.', 'Weather', 'dad_jokes_v1'),
  ('Why don''t snowmen ever lie?', 'Their noses give them away.', 'Weather', 'dad_jokes_v1'),
  ('Why was the fog so confident?', 'It rolled in like it owned the place.', 'Weather', 'dad_jokes_v1'),
  ('Why was the rain so chatty?', 'It had a lot of pour conversations.', 'Weather', 'dad_jokes_v1'),
  ('Why don''t tornadoes ever apologize?', 'They just blow over.', 'Weather', 'dad_jokes_v1'),
  ('What do you call a snowman in July?', 'A puddle.', 'Holidays', 'dad_jokes_v1'),
  ('What do you call Santa''s helpers?', 'Subordinate clauses.', 'Holidays', 'dad_jokes_v1'),
  ('Why was the Christmas tree so bad at sewing?', 'It kept dropping its needles.', 'Holidays', 'dad_jokes_v1'),
  ('What do reindeer say before telling a joke?', 'This one''s gonna sleigh you.', 'Holidays', 'dad_jokes_v1'),
  ('Why did the pumpkin go to the doctor?', 'It had a gourd-y throat.', 'Holidays', 'dad_jokes_v1'),
  ('Why don''t ghosts get hired?', 'They keep going through interviews.', 'Holidays', 'dad_jokes_v1'),
  ('What''s a witch''s favorite subject?', 'Spelling.', 'Holidays', 'dad_jokes_v1'),
  ('Why was the Thanksgiving turkey in the band?', 'It had the drumsticks.', 'Holidays', 'dad_jokes_v1'),
  ('Why did the Easter egg hide?', 'It was a little chicken.', 'Holidays', 'dad_jokes_v1'),
  ('What did the Valentine card say to the stamp?', 'Stick with me and we''ll go places.', 'Holidays', 'dad_jokes_v1'),
  ('Why did the candy cane go to the gym?', 'To stay in shape for the holidays.', 'Holidays', 'dad_jokes_v1'),
  ('Why was the New Year so dramatic?', 'It always went out with a bang.', 'Holidays', 'dad_jokes_v1'),
  ('Why don''t dads tell jokes about pizza?', 'They''re too cheesy.', 'Family', 'dad_jokes_v1'),
  ('Why did dad bring a knife to the BBQ?', 'To make some cuts.', 'Family', 'dad_jokes_v1'),
  ('What did the dad ocean say to the kid ocean?', 'Nothing — they just waved.', 'Family', 'dad_jokes_v1'),
  ('Why did dad take a ruler to bed?', 'To see how long he slept.', 'Family', 'dad_jokes_v1'),
  ('What''s a dad''s favorite type of music?', 'Pop.', 'Family', 'dad_jokes_v1'),
  ('Why is a dad''s wallet like an onion?', 'When you open it, you cry.', 'Family', 'dad_jokes_v1'),
  ('Why don''t dads ever lose at hide and seek?', 'They always say "I''ll be in the garage."', 'Family', 'dad_jokes_v1'),
  ('Why are dad jokes so bad?', 'They''re a-pa-rently rough.', 'Family', 'dad_jokes_v1'),
  ('What do you call a dad who fell through the ice?', 'A pop-sicle.', 'Family', 'dad_jokes_v1'),
  ('Why did dad fail his driving test?', 'He didn''t have the patience to merge lanes.', 'Family', 'dad_jokes_v1'),
  ('Why did dad bring a calendar to the barbecue?', 'He wanted to make some plans.', 'Family', 'dad_jokes_v1'),
  ('Why did dad name his dog Five Miles?', 'So he could say he walks five miles every morning.', 'Family', 'dad_jokes_v1')
on conflict (setup, punchline) do update set
  category = excluded.category,
  seed_source = excluded.seed_source;
